name: BukkitBugSnag
version: 1.1.3
author: theminecoder
main: me.theminecoder.bug.BukkitBugSnag
load: STARTUP
commands:
  bugsnagtest:
    permission: bukkitbugsnag.test
permissions:
  bukkitbugsnag.test:
    default: op